imports:
    - { resource: security.yml }
    - { resource: "@RPGBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en
    env(SESSION_DIR): '%kernel.project_dir%/var/sessions'
    env(MYSQL_HOST): 127.0.0.1
    database_port: null
    env(MYSQL_USER): root
    env(MYSQL_PASSWORD): null
    env(MYSQL_DATABASE): online_game

    secret: 2211e14525b768f4fd27365e29ceb953619c588e

framework:
    #esi: ~
    #translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
#    serializer: { enable_annotations: true }
    templating:
        engines: ['twig']
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: "%env(SESSION_DIR)%"
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: pdo_mysql
        host: "%env(MYSQL_HOST)%"
        port: '%database_port%'
        dbname: "%env(MYSQL_DATABASE)%"
        user: "%env(MYSQL_USER)%"
        password: "%env(MYSQL_PASSWORD)%"
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.project_dir%/var/data/data.sqlite"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

doctrine_migrations:
    dir_name: "%kernel.root_dir%/DoctrineMigrations"
    namespace:  Migrations
    table_name: migration_versions
    name: Application Migrations

fos_rest:
    param_fetcher_listener: true
    allowed_methods_listener: true
    body_converter:
        enabled: true
    routing_loader:
        default_format:       json
        include_format:       false
    serializer:
        groups:               [external]
        serialize_null:       true
    view:
        view_response_listener: 'force'
        default_engine:       twig
        formats:
            json: true
            xml:  true
        templating_formats:
            html: false
    format_listener:
        rules:
            # setting fallback_format to json means that instead of considering the next rule in case of a priority mismatch, json will be used
            - { path: '^/documentation', priorities: ['html'], fallback_format: json, prefer_extension: false }
            # default fallback to send what it can
            - { path: '^/api', priorities: [ 'json'], fallback_format: json, prefer_extension: true }
            - { path: '^/', priorities: [ 'html', 'json'], fallback_format: html, prefer_extension: true }


jms_serializer:
    metadata:
        directories:
            APP:
                namespace_prefix: "RPGBundle"
                path: "@RPGBundle/Resources/config/serializer/"
    handlers:
        datetime:
            default_format: "c" # ISO8601