rpg:
    resource: "@RPGBundle/Resources/config/routing.yml"
    prefix:   /

api:
  resource: "@RPGBundle/Controller/Api/"
  type:     annotation

NelmioApiDocBundle:
  resource: "@NelmioApiDocBundle/Resources/config/routing.yml"
  prefix: /api/doc