RPGBundle\Entity\Monster:
  exclusion_policy: ALL
  properties:
    id:
      expose: true
      serialized_name: "id"
      type: integer
      groups: ["external"]
    name:
      expose: true
      serialized_name: "name"
      type: string
      groups: ["external"]
    hitMin:
      expose: true
      serialized_name: "hitMin"
      type: integer
      groups: ["external"]
    hitMax:
      expose: true
      serialized_name: "hitMax"
      type: integer
      groups: ["external"]
    life:
      expose: true
      serialized_name: "life"
      type: integer
      groups: ["external"]